# Generated by Django 3.2.5 on 2021-08-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttruckapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(choices=[('employee_package', 'EMPLOYEE PACKAGE'), ('total_veg_package', 'TOTAL VEG PACKAGE')], max_length=50),
        ),
        migrations.CreateModel(
            name='Product_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ordered', models.BooleanField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('checkout', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttruckapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Package_product_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('employee_package', 'EMPLOYEE PACKAGE'), ('total_veg_package', 'TOTAL VEG PACKAGE')], max_length=50)),
                ('week', models.CharField(choices=[('first_week', 'FIRST WEEK'), ('second_week', 'SECOND WEEK'), ('third_week', 'THIRD WEEK'), ('fourth_week', 'FOURTH WEEK')], max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('checkout', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttruckapp.customers')),
            ],
        ),
    ]
