# Generated by Django 3.2.5 on 2021-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttruckapp', '0004_auto_20210805_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_package_price_historys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_product', models.CharField(max_length=100)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
