# Generated by Django 3.2.5 on 2021-08-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttruckapp', '0005_product_package_price_historys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttruckapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('lunch_time', models.IntegerField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttruckapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Email_otps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('validated', models.BooleanField()),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('forgot', models.BooleanField()),
                ('forgot_logged', models.BooleanField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttruckapp.customers')),
            ],
        ),
    ]
